fill ~1 ~ ~1 ~11 ~3 ~16 air replace
fill ~11 ~ ~1 ~23 ~3 ~16 air replace
fill ~11 ~ ~16 ~23 ~3 ~33 air replace
fill ~1 ~ ~16 ~11 ~3 ~33 air replace
fill ~1 ~-1 ~1 ~11 ~-1 ~16 minecraft:bedrock replace
fill ~11 ~-1 ~1 ~23 ~-1 ~16 minecraft:bedrock replace
fill ~11 ~-1 ~16 ~23 ~-1 ~33 minecraft:bedrock replace
fill ~1 ~-1 ~16 ~11 ~-1 ~33 minecraft:bedrock replace
fill ~1 ~ ~1 ~1 ~3 ~1 minecraft:bedrock replace
fill ~1 ~ ~2 ~1 ~3 ~2 minecraft:bedrock replace
fill ~1 ~ ~3 ~1 ~3 ~3 minecraft:bedrock replace
fill ~1 ~ ~4 ~1 ~3 ~4 minecraft:bedrock replace
fill ~1 ~ ~5 ~1 ~3 ~5 minecraft:bedrock replace
fill ~1 ~ ~6 ~1 ~3 ~6 minecraft:bedrock replace
fill ~1 ~ ~7 ~1 ~3 ~7 minecraft:bedrock replace
fill ~1 ~ ~8 ~1 ~3 ~8 minecraft:bedrock replace
fill ~1 ~ ~9 ~1 ~3 ~9 minecraft:bedrock replace
setblock ~1 ~ ~10 spawner{SpawnData:{id:zombie,HandItems:[{Count:1,id:stone_sword},{}],ArmorItems:[{Count:1,id:iron_boots},{Count:1,id:leather_leggings},{Count:1,id:leather_chestplate,tag:{display:{color:8991416}}},{Count:1,id:creeper_head}],CustomName:"Denko"}, SpawnRange: 20, SpawnCount: 5, MaxNearbyEntities: 5, Delay: 0, RequiredPlayerRange: 20} replace
fill ~1 ~1 ~10 ~1 ~3 ~10 minecraft:bedrock replace
fill ~1 ~ ~11 ~1 ~3 ~11 minecraft:bedrock replace
fill ~1 ~ ~12 ~1 ~3 ~12 minecraft:bedrock replace
fill ~1 ~ ~13 ~1 ~3 ~13 minecraft:bedrock replace
fill ~1 ~ ~14 ~1 ~3 ~14 minecraft:bedrock replace
fill ~1 ~ ~15 ~1 ~3 ~15 minecraft:bedrock replace
fill ~1 ~ ~16 ~1 ~3 ~16 minecraft:bedrock replace
fill ~1 ~ ~17 ~1 ~3 ~17 minecraft:bedrock replace
fill ~1 ~ ~18 ~1 ~3 ~18 minecraft:bedrock replace
setblock ~1 ~ ~19 spawner{SpawnData:{id:zombie,HandItems:[{Count:1,id:stone_sword},{}],ArmorItems:[{Count:1,id:iron_boots},{Count:1,id:leather_leggings},{Count:1,id:leather_chestplate,tag:{display:{color:8991416}}},{Count:1,id:creeper_head}],CustomName:"Denko"}, SpawnRange: 20, SpawnCount: 5, MaxNearbyEntities: 5, Delay: 0, RequiredPlayerRange: 20} replace
fill ~1 ~1 ~19 ~1 ~3 ~19 minecraft:bedrock replace
fill ~1 ~ ~20 ~1 ~3 ~20 minecraft:bedrock replace
fill ~1 ~ ~21 ~1 ~3 ~21 minecraft:bedrock replace
fill ~1 ~ ~22 ~1 ~3 ~22 minecraft:bedrock replace
fill ~1 ~ ~23 ~1 ~3 ~23 minecraft:bedrock replace
fill ~1 ~ ~24 ~1 ~3 ~24 minecraft:bedrock replace
fill ~1 ~ ~25 ~1 ~3 ~25 minecraft:bedrock replace
fill ~1 ~ ~26 ~1 ~3 ~26 minecraft:bedrock replace
fill ~1 ~ ~27 ~1 ~3 ~27 minecraft:bedrock replace
fill ~1 ~ ~28 ~1 ~3 ~28 minecraft:bedrock replace
fill ~1 ~ ~29 ~1 ~3 ~29 minecraft:bedrock replace
fill ~1 ~ ~30 ~1 ~3 ~30 minecraft:bedrock replace
fill ~1 ~ ~31 ~1 ~3 ~31 minecraft:bedrock replace
fill ~1 ~ ~32 ~1 ~3 ~32 minecraft:bedrock replace
fill ~1 ~ ~33 ~1 ~3 ~33 minecraft:bedrock replace
fill ~2 ~ ~1 ~2 ~3 ~1 minecraft:bedrock replace
fill ~2 ~ ~2 ~2 ~3 ~2 minecraft:bedrock replace
fill ~2 ~ ~3 ~2 ~3 ~3 minecraft:bedrock replace
fill ~2 ~ ~4 ~2 ~3 ~4 minecraft:bedrock replace
setblock ~2 ~ ~5 chest{Items: [{Slot: 0, id: cooked_beef, Count: 1, tag: {}}, {Slot: 1, id: arrow, Count: 1, tag: {}}, {Slot: 2, id: bread, Count: 4, tag: {}}, {Slot: 3, id: golden_axe, Count: 1, tag: {}}, {Slot: 4, id: stone_axe, Count: 1, tag: {Enchantments: [{id: fire_aspect, lvl: 1}]}}, {Slot: 5, id: bow, Count: 1, tag: {}}, {Slot: 6, id: bow, Count: 1, tag: {}}]} replace
fill ~2 ~ ~6 ~2 ~3 ~6 minecraft:bedrock replace
fill ~2 ~ ~7 ~2 ~3 ~7 minecraft:bedrock replace
fill ~2 ~ ~8 ~2 ~3 ~8 minecraft:bedrock replace
fill ~2 ~ ~9 ~2 ~3 ~9 minecraft:bedrock replace
fill ~2 ~ ~10 ~2 ~3 ~10 minecraft:bedrock replace
fill ~2 ~ ~11 ~2 ~3 ~11 minecraft:bedrock replace
fill ~2 ~ ~12 ~2 ~3 ~12 minecraft:bedrock replace
fill ~2 ~ ~14 ~2 ~3 ~14 minecraft:bedrock replace
fill ~2 ~ ~15 ~2 ~3 ~15 minecraft:bedrock replace
setblock ~2 ~ ~16 chest{Items: [{Slot: 0, id: golden_axe, Count: 1, tag: {}}, {Slot: 1, id: iron_axe, Count: 1, tag: {}}, {Slot: 2, id: arrow, Count: 4, tag: {}}, {Slot: 3, id: cooked_beef, Count: 8, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}, {Slot: 5, id: stone_axe, Count: 1, tag: {}}]} replace
fill ~2 ~ ~17 ~2 ~3 ~17 minecraft:bedrock replace
fill ~2 ~ ~18 ~2 ~3 ~18 minecraft:bedrock replace
fill ~2 ~ ~19 ~2 ~3 ~19 minecraft:bedrock replace
fill ~2 ~ ~20 ~2 ~3 ~20 minecraft:bedrock replace
fill ~2 ~ ~21 ~2 ~3 ~21 minecraft:bedrock replace
fill ~2 ~ ~22 ~2 ~3 ~22 minecraft:bedrock replace
fill ~2 ~ ~23 ~2 ~3 ~23 minecraft:bedrock replace
fill ~2 ~ ~24 ~2 ~3 ~24 minecraft:bedrock replace
fill ~2 ~ ~25 ~2 ~3 ~25 minecraft:bedrock replace
fill ~2 ~ ~26 ~2 ~3 ~26 minecraft:bedrock replace
fill ~2 ~ ~27 ~2 ~3 ~27 minecraft:bedrock replace
fill ~2 ~ ~28 ~2 ~3 ~28 minecraft:bedrock replace
fill ~2 ~ ~29 ~2 ~3 ~29 minecraft:bedrock replace
fill ~2 ~ ~30 ~2 ~3 ~30 minecraft:bedrock replace
fill ~2 ~ ~31 ~2 ~3 ~31 minecraft:bedrock replace
fill ~2 ~ ~32 ~2 ~3 ~32 minecraft:bedrock replace
fill ~2 ~ ~33 ~2 ~3 ~33 minecraft:bedrock replace
fill ~3 ~ ~1 ~3 ~3 ~1 minecraft:bedrock replace
fill ~3 ~ ~2 ~3 ~3 ~2 minecraft:bedrock replace
setblock ~3 ~ ~7 chest{Items: [{Slot: 0, id: arrow, Count: 2, tag: {}}, {Slot: 1, id: iron_axe, Count: 1, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {Potion: minecraft:fire_resistance}}, {Slot: 3, id: splash_potion, Count: 1, tag: {Potion: minecraft:regeneration}}, {Slot: 4, id: cooked_beef, Count: 5, tag: {}}, {Slot: 5, id: cooked_beef, Count: 1, tag: {}}, {Slot: 6, id: arrow, Count: 2, tag: {}}]} replace
setblock ~3 ~ ~9 chest{Items: [{Slot: 0, id: iron_helmet, Count: 1, tag: {}}, {Slot: 1, id: bow, Count: 1, tag: {}}, {Slot: 2, id: iron_axe, Count: 1, tag: {}}, {Slot: 3, id: iron_boots, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {Potion: minecraft:regeneration}}, {Slot: 5, id: splash_potion, Count: 1, tag: {Potion: minecraft:regeneration}}, {Slot: 6, id: stone_axe, Count: 1, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {Potion: minecraft:long_weakness}}, {Slot: 8, id: golden_axe, Count: 1, tag: {}}, {Slot: 9, id: splash_potion, Count: 1, tag: {}}, {Slot: 10, id: golden_axe, Count: 1, tag: {}}, {Slot: 11, id: splash_potion, Count: 1, tag: {Potion: minecraft:fire_resistance}}, {Slot: 12, id: iron_helmet, Count: 1, tag: {}}, {Slot: 13, id: bread, Count: 4, tag: {}}, {Slot: 14, id: splash_potion, Count: 1, tag: {}}, {Slot: 15, id: splash_potion, Count: 1, tag: {}}, {Slot: 16, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~3 ~ ~11 ~3 ~3 ~11 minecraft:bedrock replace
fill ~3 ~ ~20 ~3 ~3 ~20 minecraft:bedrock replace
fill ~3 ~ ~23 ~3 ~3 ~23 minecraft:bedrock replace
fill ~3 ~ ~26 ~3 ~3 ~26 minecraft:bedrock replace
fill ~3 ~ ~32 ~3 ~3 ~32 minecraft:bedrock replace
fill ~3 ~ ~33 ~3 ~3 ~33 minecraft:bedrock replace
fill ~4 ~ ~1 ~4 ~3 ~1 minecraft:bedrock replace
fill ~4 ~ ~2 ~4 ~3 ~2 minecraft:bedrock replace
setblock ~4 ~ ~3 chest{Items: [{Slot: 0, id: splash_potion, Count: 1, tag: {Potion: minecraft:regeneration}}, {Slot: 1, id: splash_potion, Count: 1, tag: {Potion: minecraft:night_vision}}, {Slot: 2, id: golden_axe, Count: 1, tag: {}}, {Slot: 3, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~4 ~ ~5 ~4 ~3 ~5 minecraft:bedrock replace
fill ~4 ~ ~6 ~4 ~3 ~6 minecraft:bedrock replace
fill ~4 ~ ~7 ~4 ~3 ~7 minecraft:bedrock replace
fill ~4 ~ ~8 ~4 ~3 ~8 minecraft:bedrock replace
fill ~4 ~ ~12 ~4 ~3 ~12 minecraft:bedrock replace
fill ~4 ~ ~13 ~4 ~3 ~13 minecraft:bedrock replace
setblock ~4 ~ ~16 chest{Items: [{Slot: 0, id: golden_axe, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}, {Slot: 2, id: bow, Count: 1, tag: {}}, {Slot: 3, id: bread, Count: 2, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}, {Slot: 5, id: splash_potion, Count: 1, tag: {}}, {Slot: 6, id: cooked_beef, Count: 7, tag: {}}, {Slot: 7, id: golden_boots, Count: 1, tag: {}}, {Slot: 8, id: arrow, Count: 3, tag: {}}, {Slot: 9, id: iron_boots, Count: 1, tag: {}}, {Slot: 10, id: stone_axe, Count: 1, tag: {}}, {Slot: 11, id: splash_potion, Count: 1, tag: {}}, {Slot: 12, id: cooked_beef, Count: 4, tag: {}}, {Slot: 13, id: arrow, Count: 4, tag: {}}]} replace
fill ~4 ~ ~17 ~4 ~3 ~17 minecraft:bedrock replace
setblock ~4 ~ ~18 chest{Items: [{Slot: 0, id: arrow, Count: 10, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~4 ~ ~23 ~4 ~3 ~23 minecraft:bedrock replace
setblock ~4 ~ ~25 chest{Items: [{Slot: 0, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 1, id: cooked_beef, Count: 7, tag: {}}, {Slot: 2, id: bread, Count: 9, tag: {}}, {Slot: 3, id: iron_leggings, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}, {id: unbreaking, lvl: 1}]}}, {Slot: 4, id: iron_axe, Count: 1, tag: {}}, {Slot: 5, id: splash_potion, Count: 1, tag: {}}, {Slot: 6, id: golden_axe, Count: 1, tag: {}}, {Slot: 7, id: iron_leggings, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}, {id: unbreaking, lvl: 1}]}}, {Slot: 8, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 9, id: bow, Count: 1, tag: {Enchantments: [{id: fire_aspect, lvl: 1}, {id: looting, lvl: 1}]}}, {Slot: 10, id: golden_chestplate, Count: 1, tag: {Enchantments: [{id: thorns, lvl: 1}, {id: projectile_protection, lvl: 1}, {id: protection, lvl: 1}]}}, {Slot: 11, id: splash_potion, Count: 1, tag: {}}, {Slot: 12, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~4 ~ ~26 ~4 ~3 ~26 minecraft:bedrock replace
fill ~4 ~ ~29 ~4 ~3 ~29 minecraft:bedrock replace
setblock ~4 ~ ~31 chest{Items: [{Slot: 0, id: bow, Count: 1, tag: {}}, {Slot: 1, id: bread, Count: 3, tag: {}}, {Slot: 2, id: iron_boots, Count: 1, tag: {}}, {Slot: 3, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}, {Slot: 5, id: golden_axe, Count: 1, tag: {}}, {Slot: 6, id: arrow, Count: 3, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: bow, Count: 1, tag: {}}, {Slot: 9, id: splash_potion, Count: 1, tag: {}}, {Slot: 10, id: cooked_beef, Count: 5, tag: {}}, {Slot: 11, id: golden_axe, Count: 1, tag: {}}, {Slot: 12, id: iron_helmet, Count: 1, tag: {}}, {Slot: 13, id: splash_potion, Count: 1, tag: {}}, {Slot: 14, id: splash_potion, Count: 1, tag: {}}, {Slot: 15, id: splash_potion, Count: 1, tag: {}}, {Slot: 16, id: golden_axe, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}, {id: fire_aspect, lvl: 1}, {id: sharpness, lvl: 1}]}}, {Slot: 17, id: arrow, Count: 7, tag: {}}, {Slot: 18, id: shield, Count: 1, tag: {}}]} replace
fill ~4 ~ ~32 ~4 ~3 ~32 minecraft:bedrock replace
fill ~4 ~ ~33 ~4 ~3 ~33 minecraft:bedrock replace
fill ~5 ~ ~1 ~5 ~3 ~1 minecraft:bedrock replace
fill ~5 ~ ~2 ~5 ~3 ~2 minecraft:bedrock replace
fill ~5 ~ ~8 ~5 ~3 ~8 minecraft:bedrock replace
fill ~5 ~ ~17 ~5 ~3 ~17 minecraft:bedrock replace
fill ~5 ~ ~20 ~5 ~3 ~20 minecraft:bedrock replace
fill ~5 ~ ~23 ~5 ~3 ~23 minecraft:bedrock replace
fill ~5 ~ ~29 ~5 ~3 ~29 minecraft:bedrock replace
setblock ~5 ~ ~31 chest{Items: [{Slot: 0, id: golden_helmet, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: golden_helmet, Count: 1, tag: {}}, {Slot: 4, id: cooked_beef, Count: 7, tag: {}}, {Slot: 5, id: stone_axe, Count: 1, tag: {}}]} replace
fill ~5 ~ ~32 ~5 ~3 ~32 minecraft:bedrock replace
fill ~5 ~ ~33 ~5 ~3 ~33 minecraft:bedrock replace
fill ~6 ~ ~1 ~6 ~3 ~1 minecraft:bedrock replace
fill ~6 ~ ~2 ~6 ~3 ~2 minecraft:bedrock replace
fill ~6 ~ ~5 ~6 ~3 ~5 minecraft:bedrock replace
fill ~6 ~ ~8 ~6 ~3 ~8 minecraft:bedrock replace
fill ~6 ~ ~9 ~6 ~3 ~9 minecraft:bedrock replace
fill ~6 ~ ~10 ~6 ~3 ~10 minecraft:bedrock replace
fill ~6 ~ ~11 ~6 ~3 ~11 minecraft:bedrock replace
fill ~6 ~ ~12 ~6 ~3 ~12 minecraft:bedrock replace
fill ~6 ~ ~13 ~6 ~3 ~13 minecraft:bedrock replace
fill ~6 ~ ~14 ~6 ~3 ~14 minecraft:bedrock replace
fill ~6 ~ ~15 ~6 ~3 ~15 minecraft:bedrock replace
fill ~6 ~ ~16 ~6 ~3 ~16 minecraft:bedrock replace
fill ~6 ~ ~17 ~6 ~3 ~17 minecraft:bedrock replace
fill ~6 ~ ~20 ~6 ~3 ~20 minecraft:bedrock replace
fill ~6 ~ ~23 ~6 ~3 ~23 minecraft:bedrock replace
fill ~6 ~ ~24 ~6 ~3 ~24 minecraft:bedrock replace
fill ~6 ~ ~25 ~6 ~3 ~25 minecraft:bedrock replace
fill ~6 ~ ~26 ~6 ~3 ~26 minecraft:bedrock replace
fill ~6 ~ ~27 ~6 ~3 ~27 minecraft:bedrock replace
fill ~6 ~ ~29 ~6 ~3 ~29 minecraft:bedrock replace
fill ~6 ~ ~33 ~6 ~3 ~33 minecraft:bedrock replace
fill ~7 ~ ~1 ~7 ~3 ~1 minecraft:bedrock replace
fill ~7 ~ ~2 ~7 ~3 ~2 minecraft:bedrock replace
fill ~7 ~ ~5 ~7 ~3 ~5 minecraft:bedrock replace
setblock ~7 ~ ~13 chest{Items: [{Slot: 0, id: golden_axe, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}, {Slot: 2, id: iron_leggings, Count: 1, tag: {}}, {Slot: 3, id: bread, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~7 ~ ~14 ~7 ~3 ~14 minecraft:bedrock replace
fill ~7 ~ ~17 ~7 ~3 ~17 minecraft:bedrock replace
fill ~7 ~ ~23 ~7 ~3 ~23 minecraft:bedrock replace
fill ~7 ~ ~29 ~7 ~3 ~29 minecraft:bedrock replace
setblock ~7 ~ ~30 chest{Items: [{Slot: 0, id: golden_axe, Count: 1, tag: {Enchantments: [{id: fire_aspect, lvl: 1}, {id: looting, lvl: 1}, {id: sharpness, lvl: 1}]}}, {Slot: 1, id: golden_boots, Count: 1, tag: {}}, {Slot: 2, id: iron_axe, Count: 1, tag: {Enchantments: [{id: looting, lvl: 1}, {id: unbreaking, lvl: 1}, {id: fire_aspect, lvl: 1}]}}]} replace
fill ~7 ~ ~32 ~7 ~3 ~32 minecraft:bedrock replace
fill ~7 ~ ~33 ~7 ~3 ~33 minecraft:bedrock replace
fill ~8 ~ ~1 ~8 ~3 ~1 minecraft:bedrock replace
fill ~8 ~ ~2 ~8 ~3 ~2 minecraft:bedrock replace
fill ~8 ~ ~5 ~8 ~3 ~5 minecraft:bedrock replace
fill ~8 ~ ~8 ~8 ~3 ~8 minecraft:bedrock replace
fill ~8 ~ ~11 ~8 ~3 ~11 minecraft:bedrock replace
fill ~8 ~ ~14 ~8 ~3 ~14 minecraft:bedrock replace
setblock ~8 ~ ~16 chest{Items: [{Slot: 0, id: iron_boots, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: stone_axe, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {Potion: minecraft:long_weakness}}]} replace
fill ~8 ~ ~17 ~8 ~3 ~17 minecraft:bedrock replace
fill ~8 ~ ~18 ~8 ~3 ~18 minecraft:bedrock replace
fill ~8 ~ ~19 ~8 ~3 ~19 minecraft:bedrock replace
fill ~8 ~ ~20 ~8 ~3 ~20 minecraft:bedrock replace
fill ~8 ~ ~23 ~8 ~3 ~23 minecraft:bedrock replace
fill ~8 ~ ~26 ~8 ~3 ~26 minecraft:bedrock replace
fill ~8 ~ ~33 ~8 ~3 ~33 minecraft:bedrock replace
fill ~9 ~ ~1 ~9 ~3 ~1 minecraft:bedrock replace
fill ~9 ~ ~2 ~9 ~3 ~2 minecraft:bedrock replace
fill ~9 ~ ~5 ~9 ~3 ~5 minecraft:bedrock replace
fill ~9 ~ ~11 ~9 ~3 ~11 minecraft:bedrock replace
fill ~9 ~ ~14 ~9 ~3 ~14 minecraft:bedrock replace
setblock ~9 ~ ~19 chest{Items: [{Slot: 0, id: iron_axe, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: bread, Count: 6, tag: {}}, {Slot: 5, id: iron_axe, Count: 1, tag: {}}, {Slot: 6, id: golden_axe, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}]}}, {Slot: 7, id: bread, Count: 9, tag: {}}, {Slot: 8, id: cooked_beef, Count: 5, tag: {}}]} replace
fill ~9 ~ ~23 ~9 ~3 ~23 minecraft:bedrock replace
setblock ~9 ~ ~26 spawner{SpawnData:{id:zombie,HandItems:[{Count:1,id:stone_sword},{}],ArmorItems:[{Count:1,id:iron_boots},{Count:1,id:leather_leggings},{Count:1,id:leather_chestplate,tag:{display:{color:8991416}}},{Count:1,id:creeper_head}],CustomName:"Denko"}, SpawnRange: 20, SpawnCount: 5, MaxNearbyEntities: 5, Delay: 0, RequiredPlayerRange: 20} replace
fill ~9 ~1 ~26 ~9 ~3 ~26 minecraft:bedrock replace
fill ~9 ~ ~29 ~9 ~3 ~29 minecraft:bedrock replace
fill ~9 ~ ~32 ~9 ~3 ~32 minecraft:bedrock replace
fill ~9 ~ ~33 ~9 ~3 ~33 minecraft:bedrock replace
fill ~10 ~ ~1 ~10 ~3 ~1 minecraft:bedrock replace
fill ~10 ~ ~2 ~10 ~3 ~2 minecraft:bedrock replace
setblock ~10 ~ ~3 chest{Items: [{Slot: 0, id: stone_axe, Count: 1, tag: {}}, {Slot: 1, id: stone_axe, Count: 1, tag: {}}, {Slot: 2, id: cooked_beef, Count: 8, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: arrow, Count: 2, tag: {}}, {Slot: 5, id: bread, Count: 6, tag: {}}, {Slot: 6, id: arrow, Count: 8, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: golden_leggings, Count: 1, tag: {}}, {Slot: 9, id: golden_leggings, Count: 1, tag: {}}, {Slot: 10, id: arrow, Count: 2, tag: {}}, {Slot: 11, id: arrow, Count: 2, tag: {}}, {Slot: 12, id: splash_potion, Count: 1, tag: {}}, {Slot: 13, id: golden_boots, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}, {id: unbreaking, lvl: 1}]}}, {Slot: 14, id: bow, Count: 1, tag: {}}, {Slot: 15, id: stone_axe, Count: 1, tag: {}}, {Slot: 16, id: iron_leggings, Count: 1, tag: {}}, {Slot: 17, id: stone_axe, Count: 1, tag: {}}, {Slot: 18, id: splash_potion, Count: 1, tag: {}}, {Slot: 19, id: arrow, Count: 6, tag: {}}, {Slot: 20, id: iron_axe, Count: 1, tag: {}}, {Slot: 21, id: cooked_beef, Count: 9, tag: {}}]} replace
fill ~10 ~ ~5 ~10 ~3 ~5 minecraft:bedrock replace
fill ~10 ~ ~6 ~10 ~3 ~6 minecraft:bedrock replace
fill ~10 ~ ~7 ~10 ~3 ~7 minecraft:bedrock replace
fill ~10 ~ ~8 ~10 ~3 ~8 minecraft:bedrock replace
fill ~10 ~ ~9 ~10 ~3 ~9 minecraft:bedrock replace
fill ~10 ~ ~10 ~10 ~3 ~10 minecraft:bedrock replace
fill ~10 ~ ~11 ~10 ~3 ~11 minecraft:bedrock replace
fill ~10 ~ ~15 ~10 ~3 ~15 minecraft:bedrock replace
fill ~10 ~ ~16 ~10 ~3 ~16 minecraft:bedrock replace
fill ~10 ~ ~17 ~10 ~3 ~17 minecraft:bedrock replace
fill ~10 ~ ~18 ~10 ~3 ~18 minecraft:bedrock replace
fill ~10 ~ ~19 ~10 ~3 ~19 minecraft:bedrock replace
fill ~10 ~ ~20 ~10 ~3 ~20 minecraft:bedrock replace
fill ~10 ~ ~23 ~10 ~3 ~23 minecraft:bedrock replace
fill ~10 ~ ~24 ~10 ~3 ~24 minecraft:bedrock replace
fill ~10 ~ ~25 ~10 ~3 ~25 minecraft:bedrock replace
fill ~10 ~ ~26 ~10 ~3 ~26 minecraft:bedrock replace
fill ~10 ~ ~29 ~10 ~3 ~29 minecraft:bedrock replace
fill ~10 ~ ~32 ~10 ~3 ~32 minecraft:bedrock replace
fill ~10 ~ ~33 ~10 ~3 ~33 minecraft:bedrock replace
fill ~11 ~ ~1 ~11 ~3 ~1 minecraft:bedrock replace
fill ~11 ~ ~2 ~11 ~3 ~2 minecraft:bedrock replace
fill ~11 ~ ~5 ~11 ~3 ~5 minecraft:bedrock replace
setblock ~11 ~ ~6 chest{Items: [{Slot: 0, id: iron_axe, Count: 1, tag: {}}, {Slot: 1, id: bread, Count: 9, tag: {}}, {Slot: 2, id: cooked_beef, Count: 7, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: bread, Count: 6, tag: {}}, {Slot: 5, id: golden_axe, Count: 1, tag: {}}, {Slot: 6, id: cooked_beef, Count: 7, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: golden_helmet, Count: 1, tag: {}}, {Slot: 9, id: splash_potion, Count: 1, tag: {Potion: minecraft:strength}}, {Slot: 10, id: golden_helmet, Count: 1, tag: {}}, {Slot: 11, id: splash_potion, Count: 1, tag: {}}, {Slot: 12, id: stone_axe, Count: 1, tag: {}}, {Slot: 13, id: golden_axe, Count: 1, tag: {}}, {Slot: 14, id: shield, Count: 1, tag: {}}, {Slot: 15, id: golden_boots, Count: 1, tag: {}}, {Slot: 16, id: stone_axe, Count: 1, tag: {}}, {Slot: 17, id: iron_boots, Count: 1, tag: {}}, {Slot: 18, id: iron_axe, Count: 1, tag: {}}, {Slot: 19, id: shield, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}]}}, {Slot: 20, id: golden_axe, Count: 1, tag: {}}, {Slot: 21, id: bread, Count: 3, tag: {}}, {Slot: 22, id: shield, Count: 1, tag: {}}, {Slot: 23, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~11 ~ ~11 ~11 ~3 ~11 minecraft:bedrock replace
fill ~11 ~ ~14 ~11 ~3 ~14 minecraft:bedrock replace
fill ~11 ~ ~20 ~11 ~3 ~20 minecraft:bedrock replace
fill ~11 ~ ~29 ~11 ~3 ~29 minecraft:bedrock replace
setblock ~11 ~ ~30 chest{Items: [{Slot: 0, id: splash_potion, Count: 1, tag: {}}, {Slot: 1, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 2, id: golden_axe, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 5, id: golden_helmet, Count: 1, tag: {Enchantments: [{id: projectile_protection, lvl: 1}]}}, {Slot: 6, id: bow, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}]}}]} replace
fill ~11 ~ ~32 ~11 ~3 ~32 minecraft:bedrock replace
fill ~11 ~ ~33 ~11 ~3 ~33 minecraft:bedrock replace
fill ~12 ~ ~1 ~12 ~3 ~1 minecraft:bedrock replace
fill ~12 ~ ~2 ~12 ~3 ~2 minecraft:bedrock replace
fill ~12 ~ ~5 ~12 ~3 ~5 minecraft:bedrock replace
fill ~12 ~ ~6 ~12 ~3 ~6 minecraft:bedrock replace
fill ~12 ~ ~7 ~12 ~3 ~7 minecraft:bedrock replace
fill ~12 ~ ~8 ~12 ~3 ~8 minecraft:bedrock replace
setblock ~12 ~ ~10 chest{Items: [{Slot: 0, id: golden_helmet, Count: 1, tag: {}}, {Slot: 1, id: bow, Count: 1, tag: {}}, {Slot: 2, id: bow, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}, {id: fire_aspect, lvl: 1}, {id: knockback, lvl: 1}]}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: iron_axe, Count: 1, tag: {}}, {Slot: 5, id: arrow, Count: 6, tag: {}}, {Slot: 6, id: bread, Count: 4, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: splash_potion, Count: 1, tag: {}}, {Slot: 9, id: bread, Count: 2, tag: {}}, {Slot: 10, id: iron_axe, Count: 1, tag: {}}, {Slot: 11, id: splash_potion, Count: 1, tag: {}}, {Slot: 12, id: bow, Count: 1, tag: {}}, {Slot: 13, id: iron_leggings, Count: 1, tag: {}}, {Slot: 14, id: bread, Count: 7, tag: {}}, {Slot: 15, id: iron_helmet, Count: 1, tag: {}}, {Slot: 16, id: golden_axe, Count: 1, tag: {}}, {Slot: 17, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 18, id: splash_potion, Count: 1, tag: {}}, {Slot: 19, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 20, id: bow, Count: 1, tag: {}}, {Slot: 21, id: golden_axe, Count: 1, tag: {}}, {Slot: 22, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~12 ~ ~11 ~12 ~3 ~11 minecraft:bedrock replace
fill ~12 ~ ~14 ~12 ~3 ~14 minecraft:bedrock replace
setblock ~12 ~ ~16 chest{Items: [{Slot: 0, id: stone_axe, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {Potion: minecraft:strength}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: golden_chestplate, Count: 1, tag: {Enchantments: [{id: thorns, lvl: 1}]}}, {Slot: 4, id: golden_helmet, Count: 1, tag: {}}, {Slot: 5, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 6, id: stone_axe, Count: 1, tag: {}}]} replace
fill ~12 ~ ~17 ~12 ~3 ~17 minecraft:bedrock replace
fill ~12 ~ ~20 ~12 ~3 ~20 minecraft:bedrock replace
fill ~12 ~ ~21 ~12 ~3 ~21 minecraft:bedrock replace
fill ~12 ~ ~22 ~12 ~3 ~22 minecraft:bedrock replace
fill ~12 ~ ~23 ~12 ~3 ~23 minecraft:bedrock replace
fill ~12 ~ ~24 ~12 ~3 ~24 minecraft:bedrock replace
fill ~12 ~ ~25 ~12 ~3 ~25 minecraft:bedrock replace
fill ~12 ~ ~26 ~12 ~3 ~26 minecraft:bedrock replace
fill ~12 ~ ~29 ~12 ~3 ~29 minecraft:bedrock replace
fill ~12 ~ ~32 ~12 ~3 ~32 minecraft:bedrock replace
fill ~12 ~ ~33 ~12 ~3 ~33 minecraft:bedrock replace
fill ~13 ~ ~1 ~13 ~3 ~1 minecraft:bedrock replace
fill ~13 ~ ~2 ~13 ~3 ~2 minecraft:bedrock replace
setblock ~13 ~ ~9 chest{Items: [{Slot: 0, id: shield, Count: 1, tag: {}}, {Slot: 1, id: iron_helmet, Count: 1, tag: {}}, {Slot: 2, id: stone_axe, Count: 1, tag: {Enchantments: [{id: smite, lvl: 1}]}}, {Slot: 3, id: cooked_beef, Count: 6, tag: {}}, {Slot: 4, id: bread, Count: 8, tag: {}}, {Slot: 5, id: iron_axe, Count: 1, tag: {Enchantments: [{id: smite, lvl: 1}, {id: sharpness, lvl: 1}, {id: unbreaking, lvl: 1}]}}, {Slot: 6, id: stone_axe, Count: 1, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: splash_potion, Count: 1, tag: {}}, {Slot: 9, id: bread, Count: 9, tag: {}}, {Slot: 10, id: splash_potion, Count: 1, tag: {}}, {Slot: 11, id: stone_axe, Count: 1, tag: {}}, {Slot: 12, id: bread, Count: 6, tag: {}}, {Slot: 13, id: bread, Count: 7, tag: {}}, {Slot: 14, id: bow, Count: 1, tag: {}}, {Slot: 15, id: iron_boots, Count: 1, tag: {}}, {Slot: 16, id: golden_axe, Count: 1, tag: {}}, {Slot: 17, id: arrow, Count: 2, tag: {}}, {Slot: 18, id: cooked_beef, Count: 3, tag: {}}, {Slot: 19, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 20, id: splash_potion, Count: 1, tag: {}}, {Slot: 21, id: golden_axe, Count: 1, tag: {Enchantments: [{id: fire_aspect, lvl: 1}]}}, {Slot: 22, id: golden_leggings, Count: 1, tag: {}}]} replace
setblock ~13 ~ ~10 chest{Items: [{Slot: 0, id: cooked_beef, Count: 6, tag: {}}, {Slot: 1, id: stone_axe, Count: 1, tag: {}}, {Slot: 2, id: golden_helmet, Count: 1, tag: {}}, {Slot: 3, id: cooked_beef, Count: 3, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}, {Slot: 5, id: iron_axe, Count: 1, tag: {Enchantments: [{id: fire_aspect, lvl: 1}, {id: smite, lvl: 1}]}}]} replace
fill ~13 ~ ~11 ~13 ~3 ~11 minecraft:bedrock replace
setblock ~13 ~ ~13 chest{Items: [{Slot: 0, id: splash_potion, Count: 1, tag: {Potion: minecraft:strength}}, {Slot: 1, id: golden_boots, Count: 1, tag: {}}, {Slot: 2, id: golden_boots, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: cooked_beef, Count: 2, tag: {}}, {Slot: 5, id: iron_axe, Count: 1, tag: {}}, {Slot: 6, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 7, id: bow, Count: 1, tag: {}}, {Slot: 8, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 9, id: golden_helmet, Count: 1, tag: {}}, {Slot: 10, id: stone_axe, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}]}}, {Slot: 11, id: splash_potion, Count: 1, tag: {}}, {Slot: 12, id: bread, Count: 4, tag: {}}]} replace
fill ~13 ~ ~17 ~13 ~3 ~17 minecraft:bedrock replace
fill ~13 ~ ~20 ~13 ~3 ~20 minecraft:bedrock replace
fill ~13 ~ ~29 ~13 ~3 ~29 minecraft:bedrock replace
fill ~13 ~ ~32 ~13 ~3 ~32 minecraft:bedrock replace
fill ~13 ~ ~33 ~13 ~3 ~33 minecraft:bedrock replace
fill ~14 ~ ~1 ~14 ~3 ~1 minecraft:bedrock replace
fill ~14 ~ ~3 ~14 ~3 ~3 minecraft:bedrock replace
fill ~14 ~ ~4 ~14 ~3 ~4 minecraft:bedrock replace
fill ~14 ~ ~5 ~14 ~3 ~5 minecraft:bedrock replace
fill ~14 ~ ~6 ~14 ~3 ~6 minecraft:bedrock replace
fill ~14 ~ ~7 ~14 ~3 ~7 minecraft:bedrock replace
fill ~14 ~ ~8 ~14 ~3 ~8 minecraft:bedrock replace
fill ~14 ~ ~11 ~14 ~3 ~11 minecraft:bedrock replace
fill ~14 ~ ~13 ~14 ~3 ~13 minecraft:bedrock replace
fill ~14 ~ ~14 ~14 ~3 ~14 minecraft:bedrock replace
fill ~14 ~ ~15 ~14 ~3 ~15 minecraft:bedrock replace
fill ~14 ~ ~17 ~14 ~3 ~17 minecraft:bedrock replace
fill ~14 ~ ~20 ~14 ~3 ~20 minecraft:bedrock replace
fill ~14 ~ ~21 ~14 ~3 ~21 minecraft:bedrock replace
fill ~14 ~ ~22 ~14 ~3 ~22 minecraft:bedrock replace
fill ~14 ~ ~23 ~14 ~3 ~23 minecraft:bedrock replace
fill ~14 ~ ~24 ~14 ~3 ~24 minecraft:bedrock replace
fill ~14 ~ ~25 ~14 ~3 ~25 minecraft:bedrock replace
fill ~14 ~ ~26 ~14 ~3 ~26 minecraft:bedrock replace
fill ~14 ~ ~27 ~14 ~3 ~27 minecraft:bedrock replace
fill ~14 ~ ~28 ~14 ~3 ~28 minecraft:bedrock replace
fill ~14 ~ ~29 ~14 ~3 ~29 minecraft:bedrock replace
fill ~14 ~ ~32 ~14 ~3 ~32 minecraft:bedrock replace
fill ~14 ~ ~33 ~14 ~3 ~33 minecraft:bedrock replace
fill ~15 ~ ~1 ~15 ~3 ~1 minecraft:bedrock replace
fill ~15 ~ ~2 ~15 ~3 ~2 minecraft:bedrock replace
setblock ~15 ~ ~5 chest{Items: [{Slot: 0, id: shield, Count: 1, tag: {}}, {Slot: 1, id: arrow, Count: 4, tag: {}}, {Slot: 2, id: arrow, Count: 7, tag: {}}, {Slot: 3, id: arrow, Count: 6, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {Potion: minecraft:regeneration}}, {Slot: 5, id: bread, Count: 4, tag: {}}, {Slot: 6, id: cooked_beef, Count: 8, tag: {}}, {Slot: 7, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 8, id: cooked_beef, Count: 4, tag: {}}, {Slot: 9, id: stone_axe, Count: 1, tag: {}}, {Slot: 10, id: bread, Count: 2, tag: {}}]} replace
setblock ~15 ~ ~13 chest{Items: [{Slot: 0, id: cooked_beef, Count: 3, tag: {}}, {Slot: 1, id: bread, Count: 1, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}, {Slot: 5, id: splash_potion, Count: 1, tag: {}}, {Slot: 6, id: bread, Count: 9, tag: {}}, {Slot: 7, id: stone_axe, Count: 1, tag: {Enchantments: [{id: smite, lvl: 1}]}}, {Slot: 8, id: golden_chestplate, Count: 1, tag: {Enchantments: [{id: projectile_protection, lvl: 1}, {id: unbreaking, lvl: 1}]}}, {Slot: 9, id: golden_helmet, Count: 1, tag: {}}, {Slot: 10, id: arrow, Count: 1, tag: {}}, {Slot: 11, id: iron_leggings, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}, {id: projectile_protection, lvl: 1}]}}, {Slot: 12, id: cooked_beef, Count: 3, tag: {}}, {Slot: 13, id: splash_potion, Count: 1, tag: {}}, {Slot: 14, id: splash_potion, Count: 1, tag: {}}, {Slot: 15, id: stone_axe, Count: 1, tag: {}}]} replace
fill ~15 ~ ~17 ~15 ~3 ~17 minecraft:bedrock replace
fill ~15 ~ ~20 ~15 ~3 ~20 minecraft:bedrock replace
fill ~15 ~ ~32 ~15 ~3 ~32 minecraft:bedrock replace
fill ~15 ~ ~33 ~15 ~3 ~33 minecraft:bedrock replace
fill ~16 ~ ~1 ~16 ~3 ~1 minecraft:bedrock replace
fill ~16 ~ ~2 ~16 ~3 ~2 minecraft:bedrock replace
fill ~16 ~ ~5 ~16 ~3 ~5 minecraft:bedrock replace
fill ~16 ~ ~6 ~16 ~3 ~6 minecraft:bedrock replace
fill ~16 ~ ~7 ~16 ~3 ~7 minecraft:bedrock replace
fill ~16 ~ ~8 ~16 ~3 ~8 minecraft:bedrock replace
fill ~16 ~ ~9 ~16 ~3 ~9 minecraft:bedrock replace
fill ~16 ~ ~10 ~16 ~3 ~10 minecraft:bedrock replace
fill ~16 ~ ~11 ~16 ~3 ~11 minecraft:bedrock replace
fill ~16 ~ ~12 ~16 ~3 ~12 minecraft:bedrock replace
fill ~16 ~ ~13 ~16 ~3 ~13 minecraft:bedrock replace
fill ~16 ~ ~14 ~16 ~3 ~14 minecraft:bedrock replace
fill ~16 ~ ~20 ~16 ~3 ~20 minecraft:bedrock replace
fill ~16 ~ ~23 ~16 ~3 ~23 minecraft:bedrock replace
fill ~16 ~ ~24 ~16 ~3 ~24 minecraft:bedrock replace
fill ~16 ~ ~25 ~16 ~3 ~25 minecraft:bedrock replace
fill ~16 ~ ~26 ~16 ~3 ~26 minecraft:bedrock replace
fill ~16 ~ ~27 ~16 ~3 ~27 minecraft:bedrock replace
fill ~16 ~ ~28 ~16 ~3 ~28 minecraft:bedrock replace
fill ~16 ~ ~29 ~16 ~3 ~29 minecraft:bedrock replace
fill ~16 ~ ~30 ~16 ~3 ~30 minecraft:bedrock replace
fill ~16 ~ ~31 ~16 ~3 ~31 minecraft:bedrock replace
fill ~16 ~ ~32 ~16 ~3 ~32 minecraft:bedrock replace
fill ~16 ~ ~33 ~16 ~3 ~33 minecraft:bedrock replace
fill ~17 ~ ~1 ~17 ~3 ~1 minecraft:bedrock replace
fill ~17 ~ ~2 ~17 ~3 ~2 minecraft:bedrock replace
fill ~17 ~ ~5 ~17 ~3 ~5 minecraft:bedrock replace
fill ~17 ~ ~14 ~17 ~3 ~14 minecraft:bedrock replace
fill ~17 ~ ~17 ~17 ~3 ~17 minecraft:bedrock replace
setblock ~17 ~ ~21 chest{Items: [{Slot: 0, id: bow, Count: 1, tag: {}}, {Slot: 1, id: cooked_beef, Count: 4, tag: {}}, {Slot: 2, id: golden_boots, Count: 1, tag: {}}, {Slot: 3, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}, {Slot: 5, id: bread, Count: 10, tag: {}}, {Slot: 6, id: arrow, Count: 1, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: golden_leggings, Count: 1, tag: {}}, {Slot: 9, id: arrow, Count: 1, tag: {}}, {Slot: 10, id: iron_boots, Count: 1, tag: {}}, {Slot: 11, id: arrow, Count: 5, tag: {}}, {Slot: 12, id: iron_axe, Count: 1, tag: {Enchantments: [{id: smite, lvl: 1}, {id: fire_aspect, lvl: 1}]}}, {Slot: 13, id: shield, Count: 1, tag: {}}, {Slot: 14, id: iron_axe, Count: 1, tag: {Enchantments: [{id: knockback, lvl: 1}, {id: fire_aspect, lvl: 1}]}}, {Slot: 15, id: cooked_beef, Count: 7, tag: {}}, {Slot: 16, id: cooked_beef, Count: 3, tag: {}}, {Slot: 17, id: splash_potion, Count: 1, tag: {}}, {Slot: 18, id: iron_leggings, Count: 1, tag: {Enchantments: [{id: protection, lvl: 1}, {id: thorns, lvl: 1}]}}, {Slot: 19, id: splash_potion, Count: 1, tag: {}}, {Slot: 20, id: iron_leggings, Count: 1, tag: {}}]} replace
fill ~17 ~ ~23 ~17 ~3 ~23 minecraft:bedrock replace
setblock ~17 ~ ~28 chest{Items: [{Slot: 0, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 1, id: bread, Count: 2, tag: {}}, {Slot: 2, id: arrow, Count: 5, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: bread, Count: 5, tag: {}}, {Slot: 5, id: bread, Count: 5, tag: {}}, {Slot: 6, id: arrow, Count: 8, tag: {}}, {Slot: 7, id: iron_boots, Count: 1, tag: {Enchantments: [{id: projectile_protection, lvl: 1}, {id: thorns, lvl: 1}, {id: blast_protection, lvl: 1}]}}, {Slot: 8, id: splash_potion, Count: 1, tag: {}}, {Slot: 9, id: arrow, Count: 2, tag: {}}, {Slot: 10, id: splash_potion, Count: 1, tag: {}}, {Slot: 11, id: golden_boots, Count: 1, tag: {}}]} replace
fill ~17 ~ ~32 ~17 ~3 ~32 minecraft:bedrock replace
fill ~17 ~ ~33 ~17 ~3 ~33 minecraft:bedrock replace
fill ~18 ~ ~1 ~18 ~3 ~1 minecraft:bedrock replace
fill ~18 ~ ~2 ~18 ~3 ~2 minecraft:bedrock replace
fill ~18 ~ ~5 ~18 ~3 ~5 minecraft:bedrock replace
setblock ~18 ~ ~7 chest{Items: [{Slot: 0, id: iron_axe, Count: 1, tag: {}}, {Slot: 1, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 2, id: stone_axe, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: cooked_beef, Count: 3, tag: {}}, {Slot: 5, id: golden_leggings, Count: 1, tag: {Enchantments: [{id: projectile_protection, lvl: 1}]}}, {Slot: 6, id: bow, Count: 1, tag: {}}, {Slot: 7, id: arrow, Count: 5, tag: {}}, {Slot: 8, id: iron_boots, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}]}}, {Slot: 9, id: splash_potion, Count: 1, tag: {}}, {Slot: 10, id: golden_boots, Count: 1, tag: {}}]} replace
fill ~18 ~ ~11 ~18 ~3 ~11 minecraft:bedrock replace
fill ~18 ~ ~14 ~18 ~3 ~14 minecraft:bedrock replace
setblock ~18 ~ ~15 chest{Items: [{Slot: 0, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 1, id: bow, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}, {id: looting, lvl: 1}]}}, {Slot: 2, id: iron_helmet, Count: 1, tag: {}}, {Slot: 3, id: stone_axe, Count: 1, tag: {}}, {Slot: 4, id: golden_helmet, Count: 1, tag: {}}, {Slot: 5, id: bread, Count: 3, tag: {}}, {Slot: 6, id: splash_potion, Count: 1, tag: {Potion: minecraft:night_vision}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: golden_axe, Count: 1, tag: {}}, {Slot: 9, id: iron_helmet, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}]}}, {Slot: 10, id: iron_chestplate, Count: 1, tag: {Enchantments: [{id: thorns, lvl: 1}]}}, {Slot: 11, id: stone_axe, Count: 1, tag: {}}, {Slot: 12, id: iron_axe, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}, {id: looting, lvl: 1}]}}]} replace
fill ~18 ~ ~17 ~18 ~3 ~17 minecraft:bedrock replace
fill ~18 ~ ~18 ~18 ~3 ~18 minecraft:bedrock replace
fill ~18 ~ ~19 ~18 ~3 ~19 minecraft:bedrock replace
fill ~18 ~ ~20 ~18 ~3 ~20 minecraft:bedrock replace
fill ~18 ~ ~21 ~18 ~3 ~21 minecraft:bedrock replace
fill ~18 ~ ~22 ~18 ~3 ~22 minecraft:bedrock replace
fill ~18 ~ ~24 ~18 ~3 ~24 minecraft:bedrock replace
fill ~18 ~ ~25 ~18 ~3 ~25 minecraft:bedrock replace
fill ~18 ~ ~26 ~18 ~3 ~26 minecraft:bedrock replace
fill ~18 ~ ~27 ~18 ~3 ~27 minecraft:bedrock replace
fill ~18 ~ ~28 ~18 ~3 ~28 minecraft:bedrock replace
fill ~18 ~ ~29 ~18 ~3 ~29 minecraft:bedrock replace
setblock ~18 ~ ~30 chest{Items: [{Slot: 0, id: splash_potion, Count: 1, tag: {Potion: minecraft:regeneration}}]} replace
fill ~18 ~ ~32 ~18 ~3 ~32 minecraft:bedrock replace
fill ~18 ~ ~33 ~18 ~3 ~33 minecraft:bedrock replace
fill ~19 ~ ~1 ~19 ~3 ~1 minecraft:bedrock replace
fill ~19 ~ ~2 ~19 ~3 ~2 minecraft:bedrock replace
fill ~19 ~ ~5 ~19 ~3 ~5 minecraft:bedrock replace
fill ~19 ~ ~8 ~19 ~3 ~8 minecraft:bedrock replace
fill ~19 ~ ~11 ~19 ~3 ~11 minecraft:bedrock replace
setblock ~19 ~ ~12 chest{Items: [{Slot: 0, id: iron_leggings, Count: 1, tag: {}}, {Slot: 1, id: golden_leggings, Count: 1, tag: {}}]} replace
fill ~19 ~ ~14 ~19 ~3 ~14 minecraft:bedrock replace
setblock ~19 ~ ~26 chest{Items: [{Slot: 0, id: golden_leggings, Count: 1, tag: {}}, {Slot: 1, id: stone_axe, Count: 1, tag: {}}, {Slot: 2, id: bow, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {Potion: minecraft:strength}}, {Slot: 4, id: iron_chestplate, Count: 1, tag: {}}, {Slot: 5, id: splash_potion, Count: 1, tag: {Potion: minecraft:fire_resistance}}, {Slot: 6, id: golden_boots, Count: 1, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: arrow, Count: 8, tag: {}}, {Slot: 9, id: splash_potion, Count: 1, tag: {}}, {Slot: 10, id: stone_axe, Count: 1, tag: {}}, {Slot: 11, id: splash_potion, Count: 1, tag: {}}, {Slot: 12, id: golden_boots, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}]}}, {Slot: 13, id: golden_leggings, Count: 1, tag: {}}, {Slot: 14, id: iron_axe, Count: 1, tag: {}}, {Slot: 15, id: bread, Count: 2, tag: {}}, {Slot: 16, id: stone_axe, Count: 1, tag: {}}, {Slot: 17, id: stone_axe, Count: 1, tag: {}}, {Slot: 18, id: iron_axe, Count: 1, tag: {}}, {Slot: 19, id: iron_axe, Count: 1, tag: {}}, {Slot: 20, id: golden_chestplate, Count: 1, tag: {}}]} replace
setblock ~19 ~ ~27 chest{Items: [{Slot: 0, id: shield, Count: 1, tag: {Enchantments: [{id: protection, lvl: 1}, {id: projectile_protection, lvl: 1}, {id: thorns, lvl: 1}]}}, {Slot: 1, id: iron_axe, Count: 1, tag: {Enchantments: [{id: sharpness, lvl: 1}, {id: knockback, lvl: 1}]}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: iron_leggings, Count: 1, tag: {}}, {Slot: 5, id: splash_potion, Count: 1, tag: {}}, {Slot: 6, id: bow, Count: 1, tag: {}}, {Slot: 7, id: bow, Count: 1, tag: {}}, {Slot: 8, id: iron_boots, Count: 1, tag: {}}, {Slot: 9, id: iron_axe, Count: 1, tag: {}}, {Slot: 10, id: iron_axe, Count: 1, tag: {}}, {Slot: 11, id: cooked_beef, Count: 3, tag: {}}, {Slot: 12, id: bread, Count: 10, tag: {}}, {Slot: 13, id: bread, Count: 2, tag: {}}, {Slot: 14, id: bow, Count: 1, tag: {}}, {Slot: 15, id: cooked_beef, Count: 1, tag: {}}, {Slot: 16, id: stone_axe, Count: 1, tag: {}}, {Slot: 17, id: splash_potion, Count: 1, tag: {}}, {Slot: 18, id: arrow, Count: 4, tag: {}}, {Slot: 19, id: bow, Count: 1, tag: {}}, {Slot: 20, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~19 ~ ~32 ~19 ~3 ~32 minecraft:bedrock replace
fill ~19 ~ ~33 ~19 ~3 ~33 minecraft:bedrock replace
fill ~20 ~ ~1 ~20 ~3 ~1 minecraft:bedrock replace
fill ~20 ~ ~2 ~20 ~3 ~2 minecraft:bedrock replace
fill ~20 ~ ~5 ~20 ~3 ~5 minecraft:bedrock replace
fill ~20 ~ ~6 ~20 ~3 ~6 minecraft:bedrock replace
fill ~20 ~ ~7 ~20 ~3 ~7 minecraft:bedrock replace
fill ~20 ~ ~8 ~20 ~3 ~8 minecraft:bedrock replace
fill ~20 ~ ~11 ~20 ~3 ~11 minecraft:bedrock replace
fill ~20 ~ ~14 ~20 ~3 ~14 minecraft:bedrock replace
setblock ~20 ~ ~15 chest{Items: [{Slot: 0, id: bow, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: splash_potion, Count: 1, tag: {}}, {Slot: 5, id: arrow, Count: 3, tag: {}}, {Slot: 6, id: golden_boots, Count: 1, tag: {}}, {Slot: 7, id: splash_potion, Count: 1, tag: {}}, {Slot: 8, id: bread, Count: 8, tag: {}}, {Slot: 9, id: splash_potion, Count: 1, tag: {}}, {Slot: 10, id: splash_potion, Count: 1, tag: {Potion: minecraft:night_vision}}, {Slot: 11, id: cooked_beef, Count: 3, tag: {}}, {Slot: 12, id: splash_potion, Count: 1, tag: {}}, {Slot: 13, id: iron_axe, Count: 1, tag: {}}, {Slot: 14, id: splash_potion, Count: 1, tag: {}}, {Slot: 15, id: bow, Count: 1, tag: {}}, {Slot: 16, id: bow, Count: 1, tag: {}}, {Slot: 17, id: bow, Count: 1, tag: {}}, {Slot: 18, id: stone_axe, Count: 1, tag: {Enchantments: [{id: looting, lvl: 1}]}}, {Slot: 19, id: arrow, Count: 4, tag: {}}, {Slot: 20, id: iron_chestplate, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}, {id: thorns, lvl: 1}, {id: protection, lvl: 1}]}}, {Slot: 21, id: bread, Count: 8, tag: {}}, {Slot: 22, id: cooked_beef, Count: 4, tag: {}}, {Slot: 23, id: arrow, Count: 6, tag: {}}]} replace
fill ~20 ~ ~17 ~20 ~3 ~17 minecraft:bedrock replace
fill ~20 ~ ~18 ~20 ~3 ~18 minecraft:bedrock replace
fill ~20 ~ ~19 ~20 ~3 ~19 minecraft:bedrock replace
fill ~20 ~ ~20 ~20 ~3 ~20 minecraft:bedrock replace
fill ~20 ~ ~21 ~20 ~3 ~21 minecraft:bedrock replace
fill ~20 ~ ~22 ~20 ~3 ~22 minecraft:bedrock replace
fill ~20 ~ ~23 ~20 ~3 ~23 minecraft:bedrock replace
fill ~20 ~ ~24 ~20 ~3 ~24 minecraft:bedrock replace
fill ~20 ~ ~25 ~20 ~3 ~25 minecraft:bedrock replace
fill ~20 ~ ~26 ~20 ~3 ~26 minecraft:bedrock replace
fill ~20 ~ ~27 ~20 ~3 ~27 minecraft:bedrock replace
fill ~20 ~ ~28 ~20 ~3 ~28 minecraft:bedrock replace
fill ~20 ~ ~29 ~20 ~3 ~29 minecraft:bedrock replace
setblock ~20 ~ ~30 chest{Items: [{Slot: 0, id: arrow, Count: 3, tag: {}}, {Slot: 1, id: bread, Count: 3, tag: {}}, {Slot: 2, id: cooked_beef, Count: 5, tag: {}}, {Slot: 3, id: iron_leggings, Count: 1, tag: {}}]} replace
fill ~20 ~ ~32 ~20 ~3 ~32 minecraft:bedrock replace
fill ~20 ~ ~33 ~20 ~3 ~33 minecraft:bedrock replace
fill ~21 ~ ~1 ~21 ~3 ~1 minecraft:bedrock replace
fill ~21 ~ ~2 ~21 ~3 ~2 minecraft:bedrock replace
setblock ~21 ~ ~6 chest{Items: [{Slot: 0, id: splash_potion, Count: 1, tag: {}}, {Slot: 1, id: arrow, Count: 7, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {Potion: minecraft:fire_resistance}}, {Slot: 4, id: arrow, Count: 8, tag: {}}, {Slot: 5, id: bow, Count: 1, tag: {}}, {Slot: 6, id: splash_potion, Count: 1, tag: {}}]} replace
setblock ~21 ~ ~7 chest{Items: [{Slot: 0, id: stone_axe, Count: 1, tag: {}}, {Slot: 1, id: splash_potion, Count: 1, tag: {}}, {Slot: 2, id: arrow, Count: 6, tag: {}}, {Slot: 3, id: splash_potion, Count: 1, tag: {}}, {Slot: 4, id: iron_axe, Count: 1, tag: {}}, {Slot: 5, id: bread, Count: 4, tag: {}}, {Slot: 6, id: golden_boots, Count: 1, tag: {}}, {Slot: 7, id: arrow, Count: 10, tag: {}}, {Slot: 8, id: splash_potion, Count: 1, tag: {}}, {Slot: 9, id: bread, Count: 7, tag: {}}, {Slot: 10, id: iron_axe, Count: 1, tag: {}}, {Slot: 11, id: cooked_beef, Count: 5, tag: {}}, {Slot: 12, id: golden_axe, Count: 1, tag: {}}, {Slot: 13, id: arrow, Count: 1, tag: {}}, {Slot: 14, id: bread, Count: 9, tag: {}}, {Slot: 15, id: iron_boots, Count: 1, tag: {}}]} replace
fill ~21 ~ ~11 ~21 ~3 ~11 minecraft:bedrock replace
fill ~21 ~ ~17 ~21 ~3 ~17 minecraft:bedrock replace
setblock ~21 ~ ~29 chest{Items: [{Slot: 0, id: splash_potion, Count: 1, tag: {}}]} replace
fill ~21 ~ ~32 ~21 ~3 ~32 minecraft:bedrock replace
fill ~21 ~ ~33 ~21 ~3 ~33 minecraft:bedrock replace
fill ~22 ~ ~1 ~22 ~3 ~1 minecraft:bedrock replace
fill ~22 ~ ~2 ~22 ~3 ~2 minecraft:bedrock replace
fill ~22 ~ ~3 ~22 ~3 ~3 minecraft:bedrock replace
fill ~22 ~ ~4 ~22 ~3 ~4 minecraft:bedrock replace
fill ~22 ~ ~5 ~22 ~3 ~5 minecraft:bedrock replace
fill ~22 ~ ~6 ~22 ~3 ~6 minecraft:bedrock replace
fill ~22 ~ ~7 ~22 ~3 ~7 minecraft:bedrock replace
fill ~22 ~ ~8 ~22 ~3 ~8 minecraft:bedrock replace
fill ~22 ~ ~9 ~22 ~3 ~9 minecraft:bedrock replace
fill ~22 ~ ~10 ~22 ~3 ~10 minecraft:bedrock replace
fill ~22 ~ ~11 ~22 ~3 ~11 minecraft:bedrock replace
fill ~22 ~ ~12 ~22 ~3 ~12 minecraft:bedrock replace
fill ~22 ~ ~13 ~22 ~3 ~13 minecraft:bedrock replace
fill ~22 ~ ~14 ~22 ~3 ~14 minecraft:bedrock replace
fill ~22 ~ ~15 ~22 ~3 ~15 minecraft:bedrock replace
fill ~22 ~ ~16 ~22 ~3 ~16 minecraft:bedrock replace
fill ~22 ~ ~17 ~22 ~3 ~17 minecraft:bedrock replace
fill ~22 ~ ~18 ~22 ~3 ~18 minecraft:bedrock replace
fill ~22 ~ ~20 ~22 ~3 ~20 minecraft:bedrock replace
fill ~22 ~ ~21 ~22 ~3 ~21 minecraft:bedrock replace
fill ~22 ~ ~22 ~22 ~3 ~22 minecraft:bedrock replace
fill ~22 ~ ~23 ~22 ~3 ~23 minecraft:bedrock replace
fill ~22 ~ ~24 ~22 ~3 ~24 minecraft:bedrock replace
fill ~22 ~ ~25 ~22 ~3 ~25 minecraft:bedrock replace
fill ~22 ~ ~26 ~22 ~3 ~26 minecraft:bedrock replace
setblock ~22 ~ ~27 chest{Items: [{Slot: 0, id: golden_helmet, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}, {id: unbreaking, lvl: 1}]}}, {Slot: 1, id: shield, Count: 1, tag: {}}, {Slot: 2, id: splash_potion, Count: 1, tag: {}}, {Slot: 3, id: golden_chestplate, Count: 1, tag: {Enchantments: [{id: unbreaking, lvl: 1}]}}, {Slot: 4, id: iron_boots, Count: 1, tag: {}}, {Slot: 5, id: cooked_beef, Count: 6, tag: {}}, {Slot: 6, id: bow, Count: 1, tag: {}}, {Slot: 7, id: golden_chestplate, Count: 1, tag: {}}, {Slot: 8, id: stone_axe, Count: 1, tag: {}}, {Slot: 9, id: splash_potion, Count: 1, tag: {}}, {Slot: 10, id: stone_axe, Count: 1, tag: {}}, {Slot: 11, id: iron_boots, Count: 1, tag: {Enchantments: [{id: blast_protection, lvl: 1}, {id: protection, lvl: 1}, {id: unbreaking, lvl: 1}]}}, {Slot: 12, id: bread, Count: 6, tag: {}}, {Slot: 13, id: arrow, Count: 10, tag: {}}, {Slot: 14, id: cooked_beef, Count: 7, tag: {}}, {Slot: 15, id: bread, Count: 1, tag: {}}, {Slot: 16, id: arrow, Count: 6, tag: {}}, {Slot: 17, id: iron_axe, Count: 1, tag: {}}, {Slot: 18, id: golden_boots, Count: 1, tag: {}}, {Slot: 19, id: bread, Count: 6, tag: {}}]} replace
setblock ~22 ~ ~28 spawner{SpawnData:{id:zombie,HandItems:[{Count:1,id:stone_sword},{}],ArmorItems:[{Count:1,id:iron_boots},{Count:1,id:leather_leggings},{Count:1,id:leather_chestplate,tag:{display:{color:8991416}}},{Count:1,id:creeper_head}],CustomName:"Denko"}, SpawnRange: 20, SpawnCount: 5, MaxNearbyEntities: 5, Delay: 0, RequiredPlayerRange: 20} replace
fill ~22 ~1 ~28 ~22 ~3 ~28 minecraft:bedrock replace
fill ~22 ~ ~29 ~22 ~3 ~29 minecraft:bedrock replace
fill ~22 ~ ~30 ~22 ~3 ~30 minecraft:bedrock replace
fill ~22 ~ ~31 ~22 ~3 ~31 minecraft:bedrock replace
fill ~22 ~ ~32 ~22 ~3 ~32 minecraft:bedrock replace
fill ~22 ~ ~33 ~22 ~3 ~33 minecraft:bedrock replace
fill ~23 ~ ~1 ~23 ~3 ~1 minecraft:bedrock replace
fill ~23 ~ ~2 ~23 ~3 ~2 minecraft:bedrock replace
fill ~23 ~ ~3 ~23 ~3 ~3 minecraft:bedrock replace
fill ~23 ~ ~4 ~23 ~3 ~4 minecraft:bedrock replace
fill ~23 ~ ~5 ~23 ~3 ~5 minecraft:bedrock replace
fill ~23 ~ ~6 ~23 ~3 ~6 minecraft:bedrock replace
fill ~23 ~ ~7 ~23 ~3 ~7 minecraft:bedrock replace
fill ~23 ~ ~8 ~23 ~3 ~8 minecraft:bedrock replace
fill ~23 ~ ~9 ~23 ~3 ~9 minecraft:bedrock replace
fill ~23 ~ ~10 ~23 ~3 ~10 minecraft:bedrock replace
fill ~23 ~ ~11 ~23 ~3 ~11 minecraft:bedrock replace
fill ~23 ~ ~12 ~23 ~3 ~12 minecraft:bedrock replace
fill ~23 ~ ~13 ~23 ~3 ~13 minecraft:bedrock replace
fill ~23 ~ ~14 ~23 ~3 ~14 minecraft:bedrock replace
fill ~23 ~ ~15 ~23 ~3 ~15 minecraft:bedrock replace
fill ~23 ~ ~16 ~23 ~3 ~16 minecraft:bedrock replace
fill ~23 ~ ~17 ~23 ~3 ~17 minecraft:bedrock replace
fill ~23 ~ ~18 ~23 ~3 ~18 minecraft:bedrock replace
fill ~23 ~ ~19 ~23 ~3 ~19 minecraft:bedrock replace
fill ~23 ~ ~20 ~23 ~3 ~20 minecraft:bedrock replace
fill ~23 ~ ~21 ~23 ~3 ~21 minecraft:bedrock replace
fill ~23 ~ ~22 ~23 ~3 ~22 minecraft:bedrock replace
fill ~23 ~ ~23 ~23 ~3 ~23 minecraft:bedrock replace
fill ~23 ~ ~24 ~23 ~3 ~24 minecraft:bedrock replace
fill ~23 ~ ~25 ~23 ~3 ~25 minecraft:bedrock replace
fill ~23 ~ ~26 ~23 ~3 ~26 minecraft:bedrock replace
fill ~23 ~ ~27 ~23 ~3 ~27 minecraft:bedrock replace
fill ~23 ~ ~28 ~23 ~3 ~28 minecraft:bedrock replace
fill ~23 ~ ~29 ~23 ~3 ~29 minecraft:bedrock replace
fill ~23 ~ ~30 ~23 ~3 ~30 minecraft:bedrock replace
fill ~23 ~ ~31 ~23 ~3 ~31 minecraft:bedrock replace
fill ~23 ~ ~32 ~23 ~3 ~32 minecraft:bedrock replace
fill ~23 ~ ~33 ~23 ~3 ~33 minecraft:bedrock replace
fill ~1 ~ ~3 ~3 ~3 ~3 air replace
fill ~23 ~ ~30 ~21 ~3 ~30 minecraft:glass replace
